---
name: Build

runs:
  using: composite

  steps:
    - name: Install Poetry
      uses: snok/install-poetry@v1

    - name: Install dependencies
      shell: bash
      run: poetry install --with=dev

    - name: Install dependencies
      shell: bash
      run: poetry build
