---
name: Semantic Release Test

on: # yamllint disable-line rule:truthy
  pull_request:

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency: release
    # permissions:
    #   id-token: write

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Python Semantic Release
        id: release
        uses: python-semantic-release/python-semantic-release@v9.8.5
        with:
          prerelease: true
          prerelease_token: pr
          commit: false
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_TOKEN }}
          repository-url: https://test.pypi.org/legacy/
        if: steps.release.outputs.released == 'true'
